// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Project3.Web.Data;
using System;

namespace Project3.Web.Migrations
{
    [DbContext(typeof(Project3DbContext))]
    [Migration("20180605023256_b")]
    partial class b
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project3.Data.Models.Comments", b =>
                {
                    b.Property<int>("coid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("cid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("createtime");

                    b.Property<string>("ip");

                    b.Property<string>("mail")
                        .IsRequired();

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("parentcoid");

                    b.HasKey("coid");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Project3.Data.Models.Contents", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("allowcomment");

                    b.Property<string>("banner");

                    b.Property<string>("content");

                    b.Property<DateTime>("createtime");

                    b.Property<string>("excerpt");

                    b.Property<int>("index");

                    b.Property<int>("parent");

                    b.Property<string>("slug");

                    b.Property<int>("status");

                    b.Property<string>("title");

                    b.Property<int>("type");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("cid");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Project3.Data.Models.Metas", b =>
                {
                    b.Property<int>("mid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("type");

                    b.HasKey("mid");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Project3.Data.Models.Options", b =>
                {
                    b.Property<string>("name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("value");

                    b.HasKey("name");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Project3.Data.Models.Relationships", b =>
                {
                    b.Property<int>("rid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("cid");

                    b.Property<int>("mid");

                    b.HasKey("rid");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Project3.Data.Models.Users", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("uid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
